# Generated by Django 6.0.3 on 2026-04-13 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin')], default='admin', max_length=20)),
                ('is_predefined', models.BooleanField(default=True, help_text='System-created predefined account (managed via create_predefined_users)')),
                ('use_shared_google_drive', models.BooleanField(default=True, help_text='When True, uses the shared lifewoodph.finance@gmail.com Drive token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User Profile',
                'verbose_name_plural': 'Admin User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
