# Generated by Django 6.0.3 on 2026-03-10 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('drive_file_name', models.CharField(max_length=500)),
                ('drive_folder_id', models.CharField(blank=True, max_length=255)),
                ('drive_folder_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending OCR'), ('processed', 'Processed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('official_receipt', 'Official Receipt'), ('sales_invoice', 'Sales Invoice (Old)'), ('delivery_receipt', 'Delivery Receipt'), ('collection_receipt', 'Collection Receipt'), ('acknowledgment_receipt', 'Acknowledgment Receipt'), ('charge_invoice', 'Charge Invoice'), ('cash_invoice', 'Cash Invoice'), ('debit_memo', 'Debit Memo'), ('credit_memo', 'Credit Memo'), ('job_order', 'Job Order'), ('purchase_order', 'Purchase Order'), ('billing_statement', 'Billing Statement'), ('statement_of_account', 'Statement of Account'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('vat_type', models.CharField(choices=[('vat', 'VAT-Registered'), ('non_vat', 'Non-VAT'), ('zero_rated', 'Zero-Rated'), ('vat_exempt', 'VAT-Exempt'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('expense_category', models.CharField(choices=[('office_supplies', 'Office Supplies'), ('meals_entertainment', 'Meals & Entertainment'), ('transportation', 'Transportation & Travel'), ('utilities', 'Utilities'), ('communication', 'Communication'), ('professional_fees', 'Professional Fees'), ('rent', 'Rent & Lease'), ('salaries', 'Salaries & Wages'), ('repairs_maintenance', 'Repairs & Maintenance'), ('taxes_licenses', 'Taxes & Licenses'), ('insurance', 'Insurance'), ('advertising', 'Advertising & Marketing'), ('miscellaneous', 'Miscellaneous'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=500)),
                ('business_address', models.TextField(blank=True)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('bir_permit_number', models.CharField(blank=True, max_length=100)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('buyer_name', models.CharField(blank=True, max_length=500)),
                ('buyer_tin', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vatable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_exempt_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zero_rated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('employee_name', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='billing.conversation')),
                ('referenced_receipts', models.ManyToManyField(blank=True, related_name='chat_messages', to='billing.receipt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
