# Generated by Django 6.0.3 on 2026-03-20 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_count', models.IntegerField(default=0)),
                ('avg_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of receipts with all mandatory BIR fields present', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('missing_tin', 'Missing TIN'), ('missing_receipt_no', 'Missing Receipt Number'), ('missing_bir_permit', 'Missing BIR Permit'), ('duplicate_receipt', 'Possible Duplicate Receipt'), ('amount_anomaly', 'Unusual Amount'), ('missing_date', 'Missing Expense Date'), ('unverified_vendor', 'Unverified Vendor'), ('over_budget', 'Over Budget'), ('vat_mismatch', 'VAT Calculation Mismatch'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('waived', 'Waived')], default='open', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='billing.receipt')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risk_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('folder_name', models.CharField(help_text='Must exactly match drive_folder_name on Receipt records', max_length=500)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'folder_name'],
                'unique_together': {('user', 'year', 'month', 'folder_name')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_month', models.CharField(max_length=2)),
                ('total_receipts', models.IntegerField(default=0)),
                ('compliant_receipts', models.IntegerField(default=0)),
                ('non_compliant', models.IntegerField(default=0)),
                ('compliance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_vat_remittable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('period_year', 'period_month')},
            },
        ),
    ]
